database.url = jdbc:mysql://aion-db:3306/aion_cs?serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
database.user = root
database.password =

chatserver.network.client.socket_address = 0.0.0.0:10241
chatserver.network.client.connect_address = 127.0.0.1:10241
chatserver.network.gameserver.socket_address = 0.0.0.0:9021
chatserver.network.gameserver.password =
