database.url = jdbc:mysql://aion-db:3306/aion_gs?serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
database.user = root
database.password =

gameserver.timezone = UTC
gameserver.network.client.socket_address = 0.0.0.0:7777
gameserver.network.client.connect_address = 127.0.0.1:7777
gameserver.network.login.address = aion-login-server:9014
gameserver.network.login.gsid = 1
gameserver.network.login.password = 1234
gameserver.network.chat.address = aion-chat-server:9021
gameserver.network.chat.password =
